theme: jekyll-theme-cayman
title: Avinhs testing things
description: Testing Jekyll things
team_members:
  -
    name: "Sarah Becker"
    role: "project lead"
    start_date: "2016-02-01"
  -
    name: "Jane Smith"
    role: maintainer
    start_date: "2018-03-15"
  -
    name: "Albert Hamilton"
    role: editor
    start_date: "2017-12-01"
team:
  - fname: Avinh
    lname: Huynh
    role: Scrum Master
  - fname: Akhil
    lname: Nandhakumar
    role: Technical Officer
  - fname: Yash
    lname: Shah
    role: Deployment Manager
  - fname: Valen
    lname: Reynolds
    role: Github Admin
  - fname: Jay
    lname: Manjrekar
    role: Design Manager
