theme: jekyll-theme-slate
title: Avinhs testing things
description: Testing Jekyll things
team:
  - fname: Avinh
    lname: Huynh
    role: Scrum Master
    - week4:
        pbl: ReadMe Timeboxing, Jekyll
        3.1: test1
        3.2: test2
        3.3: test3
      week3:
      week2:
      week1:
  - fname: Akhil
    lname: Nandhakumar
    role: Technical Officer
    - week4:
      - pbl: ReadMe Timeboxing, Jekyll
        3.1: test1
        3.2: test2
        3.3: test3
      week3:
      week2:
      week1:
- fname: Yash
    lname: Shah
    role: Deployment Manager
    - week4:
      - pbl: ReadMe Timeboxing, Jekyll
        3.1: test1
        3.2: test2
        3.3: test3
      week3:
      week2:
      week1:
  - fname: Valen
    lname: Reynolds
    role: Github Admin
    - week4:
      - pbl: ReadMe Timeboxing, Jekyll
        3.1: test1
        3.2: test2
        3.3: test3
      week3:
      week2:
      week1:
  - fname: Jay
    lname: Manjrekar
    role: Design Manager
    - week4:
      - pbl: ReadMe Timeboxing, Jekyll
        3.1: test1
        3.2: test2
        3.3: test3
      week3:
      week2:
      week1:
